### ISSUE TITLE
Import error crashes Home Assistant

### ISSUE THREAD

**Issue by fritut08** [krahabb/meross_lan#315]
Since yesterday, my home assistant instance that is being run inside a VM within Proxmox VE constantly crashes. When I turn it back on, it shuts off within approximately 90 seconds. This gives me enough time to log in and look at the logs. There are a few errors, almost all of which mention the meross_lan integration in some way. The last error message before the shutdown of the VM that I see also seems to be the most "severe" to my untrained eye. It says "Error doing job: Task exception was never retrieved".  It goes on to claim that it cannot import something called "MLUpdate".  The entire error message is contained in the spoiler.

<details>
  <summary>Error Message</summary>
 
```yaml 
Logger: homeassistant
Source: config_entries.py:2044
First occurred: 18:12:05 (1 occurrences)
Last logged: 18:12:05

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2037, in _load_integration
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/meross_lan/__init__.py", line 28, in <module>
    from .meross_device import MerossDevice
  File "/config/custom_components/meross_lan/meross_device.py", line 71, in <module>
    from .update import MLUpdate
ImportError: cannot import name 'MLUpdate' from 'custom_components.meross_lan.update' (/config/custom_components/meross_lan/update.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 95, in _async_start
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 185, in gather_with_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 183, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 847, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 865, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 967, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2044, in _load_integration
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

```

</details>
  
Am I right to assume that this integration might be the reason for the quick shutdown?

**Comment by fritut08** [comment]
Things I have tried so far:

## Deleting the integration

I cannot delete the integration within the 90 second time frame. If I click on the "delete" button wihtin HACS, it tells me to delete its configuration first, which I understand as deleting the devices created by the integration. However, if I click on the "delete" button, nothing happens before the VM shuts down. I can deactivate the devices in time but that still does not allow me to delete the integration.

## Activating debug logs

I cannot activate debug logs (like [this](https://github.com/krahabb/meross_lan/wiki/Diagnostics))  because the file editor addon that I use for editing the yaml files does not start before the VM crashes.


Does anyone know a way of doing either of these things via the Home Assistant OS's command line? That would buy me some time since the website would not have to load. Also, I can get into some sort of safe startup shell of the Home Assistant OS where it does not crash within 90 seconds. But I do not know any commands except```systemctl``` that I can execute there.

**Comment by krahabb** [comment]
Hello @fritut08,
after checking the recent issues I've seen no response on your thread (I'm pretty sure I've replied but I've likely forgot to push the 'Comment' button...)

I hope you got the issue fixed by now.. Nevertheless I guess the error was coming from a 'corrupted' file system or installation leading to some missing files (it happens more than expected)

It is very strange though the VM was completely crashing or shutting down. When any of these errors happens, the python interpreter (and HomeAssistant) itself, are well prepared to safely manage that and keep gooing

At any rate, or for future reference, it is possible to manually delete the 'custom_components/meross_lan' folder and this will prevent any further loading (at the next startup, that is)

**Comment by fritut08** [comment]
Hey @krahabb , thanks for the reply. I have actually not been able to solve this issue yet. The problem is still the same. I have one weird piece of information to add, though. The problem persists even if I restore a backup (i.e., any backup I have, really. Even very old ones from a year ago.) of the Home Assistant VM from within Proxmox VE. So, to me this seems like either there is some sort of bug that has been present in all of my backups but only started to make problems recently or my Proxmox VE is acting up... I am at a loss for ways to approach this other than reinstalling everything.

I would prefer not to close this thread unless you are sure this has nothing to do with this add-on.

**Comment by fritut08** [comment]
Today, I finally got around to deal with this problem again. So, I booted up the VM for the first time in a month and it stayed on! While it had always crashed after about 90 seconds when I created this thread, it has been up for 40 minutes now. The error message "Error doing job: Task exception was never retrieved" I mentioned in the beginning still shows up in the log after boot which is a sign for me that this integration has nothing to do with my weird issue. Therefore, even though I learned nothing and I can just hope that this was some weird behavior that never shows up again, I will close this thread.
